### ISSUE TITLE
Videos start playing midway-through

### ISSUE THREAD

**Issue by amsone** [odinecse/tunetab#4]
Can't quite figure out how to reproduce this. I initially thought this happened when a video was skipped the subsequent video would start playing from the same time location (i.e. if I'm playing video A, and skip it when it is 2:30 in, video B which is next in the queue will start playing at 2:30) but that doesn't seem to be consistent. Happy to try to reproduce this live for you sometime if that's helpful.

**Comment by odinecse** [comment]
I haven't seen this, but I have seen the "you've already voted" even when I haven't for skipping. I need to check when some of those variables are set and then passed to the client. I can imagine it's something like videos being announced to client before the videotime is reset. 

Will investigate, thanks

**Comment by odinecse** [comment]
I think I fixed this. I think part of the issue was that every time a video was playing a new ping interval was started from client to server. If a lot of people watched even a good amount of videos, that's a huge number of pings to server with current time. Anyway, also forcing time to go back to 0 in a few places.

If you notice this again I'll reopen. If this doesn't solve it then there might be some other memory leak/performance issue
