### ISSUE TITLE
Feature (removal) request: Seeking/pausing/stop/etc

### ISSUE THREAD

**Issue by amsone** [odinecse/tunetab#5]
It seems like the YT player now includes seek/pause/stop options again, but yesterday's didn't. Doesn't seeking/pausing/etc result in the viewership being out of sync? It was kind of nice lacking those, Dave remarked that it made it "more like TV" and I agree.

**Comment by odinecse** [comment]
I enabled them because I was messing around with fullscreen option. I wish there was a way I could have just volume and full screen without other controls. I think I prefer it "TV" like as well.

Also, even with no controls you can still pause by clicking on it. I could prevent this by overlaying something transparent over the video but this is technically against YT policy. If you do pause, you stay paused, but when the room goes to the next video so will your client.

PS: If you do seek (forward) everyone else in the room gets seeked ahead too.

**Comment by odinecse** [comment]
went back to minimal, decided against breaking YT policy with a prevent pause
